name: health_care
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.2
  dartz: ^0.10.1
  get_it: ^7.2.0
  dio: ^5.0.1
  data_connection_checker_nulls: ^0.0.2
  pretty_dio_logger: ^1.3.1
  retrofit: ^4.0.1
  retrofit_generator: ^5.0.0
  analyzer: ^5.2.0
  shared_preferences: ^2.0.18
  json_annotation: ^4.8.0
  smooth_page_indicator: ^1.0.1
  bottom_navy_bar: ^6.0.0
  shimmer: ^3.0.0
  conditional_builder_null_safety: ^0.0.6
  jiffy: ^5.0.0
  intl: ^0.17.0
  flutter_rating_bar: ^4.0.1
  toggle_switch: ^2.1.0
  socket_io_client: ^2.0.2
  flutter_phoenix: ^1.1.0
  pull_to_refresh: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.6.1
  build_runner: ^2.3.3


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/splash_logo.png
    - assets/images/on_boarding_logo1.jpg
    - assets/images/on_boarding_logo2.jpg
    - assets/images/google_logo_icon.png
    - assets/images/person_photo.png


  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
    - family: IconBroken
      fonts:
        - asset: assets/fonts/icons.ttf
